Added Nether Labels to menu-themes
kando-menu/menu-themes pull request #3
Opened 2024-12-02 12:18 UTC by elfi-ox

2024-12-02 12:25 UTC, yar2000T requested changes
Add your theme description and preview image to README.md. Also add file REUSE.toml (read readme file, it have detailed description)

2024-12-02 16:21 UTC, elfi-ox commented
it should be good now

2024-12-02 19:34 UTC, Schneegans requested changes
Looks good! I think only the one license identifier is off.

2024-12-02 19:34 UTC, Schneegans commented on themes/nether-labels/README.md
> +SPDX-License-Identifier: CC-BY-1.0
I think [you should use 4.0](https://creativecommons.org/licenses/by/1.0/deed.de).

```suggestion
SPDX-License-Identifier: CC-BY-4.0
```

2024-12-03 13:55 UTC, Schneegans approved these changes

2024-12-03 13:56 UTC, merged

2024-12-03 13:56 UTC, Schneegans commented
Awesome! Thank you very much!